Refactor/map screen UI
SwEnt-2024-Group-19/Activities pull request #399
Opened 2024-12-16 11:58 UTC by elvan03

In this PR,  I update the UI of the map screen.

2024-12-16 17:48 UTC, Yassyass181104 requested changes
Overrall the implementation looks very good but the only problem I can point is that the tests you have created must be moved to the unit tests folder but they seem to be complete

2024-12-16 17:48 UTC, Yassyass181104 commented on app/src/main/java/com/android/sample/ui/map/MapMarkerUtils.kt
This implementation of our own pin looks correct and very simple to use

2024-12-16 17:48 UTC, Yassyass181104 commented on app/src/main/java/com/android/sample/ui/map/Map.kt
You use the new pin implementation to have them colored depending on the category, very good.

2024-12-17 09:50 UTC, elvan03 commented
Thanks for your review Yassine! The test file is already in the unit tests folder :))

2024-12-17 09:51 UTC, Yassyass181104 approved these changes

2024-12-17 09:51 UTC, Yassyass181104 commented
> Thanks for your review Yassine! The test file is already in the unit tests folder :))

My bad, thanks for the clarification

2024-12-17 09:51 UTC, merged